/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { AppraiserService } from "../appraiser.service";
import { AppraiserCreateInput } from "./AppraiserCreateInput";
import { Appraiser } from "./Appraiser";
import { AppraiserFindManyArgs } from "./AppraiserFindManyArgs";
import { AppraiserWhereUniqueInput } from "./AppraiserWhereUniqueInput";
import { AppraiserUpdateInput } from "./AppraiserUpdateInput";
import { PropertyFindManyArgs } from "../../property/base/PropertyFindManyArgs";
import { Property } from "../../property/base/Property";
import { PropertyWhereUniqueInput } from "../../property/base/PropertyWhereUniqueInput";

export class AppraiserControllerBase {
  constructor(protected readonly service: AppraiserService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Appraiser })
  async createAppraiser(
    @common.Body() data: AppraiserCreateInput
  ): Promise<Appraiser> {
    return await this.service.createAppraiser({
      data: data,
      select: {
        createdAt: true,
        email: true,
        id: true,
        name: true,
        phone: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Appraiser] })
  @ApiNestedQuery(AppraiserFindManyArgs)
  async appraisers(@common.Req() request: Request): Promise<Appraiser[]> {
    const args = plainToClass(AppraiserFindManyArgs, request.query);
    return this.service.appraisers({
      ...args,
      select: {
        createdAt: true,
        email: true,
        id: true,
        name: true,
        phone: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Appraiser })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async appraiser(
    @common.Param() params: AppraiserWhereUniqueInput
  ): Promise<Appraiser | null> {
    const result = await this.service.appraiser({
      where: params,
      select: {
        createdAt: true,
        email: true,
        id: true,
        name: true,
        phone: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Appraiser })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateAppraiser(
    @common.Param() params: AppraiserWhereUniqueInput,
    @common.Body() data: AppraiserUpdateInput
  ): Promise<Appraiser | null> {
    try {
      return await this.service.updateAppraiser({
        where: params,
        data: data,
        select: {
          createdAt: true,
          email: true,
          id: true,
          name: true,
          phone: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Appraiser })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteAppraiser(
    @common.Param() params: AppraiserWhereUniqueInput
  ): Promise<Appraiser | null> {
    try {
      return await this.service.deleteAppraiser({
        where: params,
        select: {
          createdAt: true,
          email: true,
          id: true,
          name: true,
          phone: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/properties")
  @ApiNestedQuery(PropertyFindManyArgs)
  async findProperties(
    @common.Req() request: Request,
    @common.Param() params: AppraiserWhereUniqueInput
  ): Promise<Property[]> {
    const query = plainToClass(PropertyFindManyArgs, request.query);
    const results = await this.service.findProperties(params.id, {
      ...query,
      select: {
        address: true,

        agent: {
          select: {
            id: true,
          },
        },

        appraiser: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        description: true,
        id: true,
        price: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/properties")
  async connectProperties(
    @common.Param() params: AppraiserWhereUniqueInput,
    @common.Body() body: PropertyWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      properties: {
        connect: body,
      },
    };
    await this.service.updateAppraiser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/properties")
  async updateProperties(
    @common.Param() params: AppraiserWhereUniqueInput,
    @common.Body() body: PropertyWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      properties: {
        set: body,
      },
    };
    await this.service.updateAppraiser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/properties")
  async disconnectProperties(
    @common.Param() params: AppraiserWhereUniqueInput,
    @common.Body() body: PropertyWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      properties: {
        disconnect: body,
      },
    };
    await this.service.updateAppraiser({
      where: params,
      data,
      select: { id: true },
    });
  }
}
